name: Publish package to GitHub Packages
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v2
      
      - name: Step 2 - Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version:11
        
      - name: Step 3 - Have GitHub Actions build maven project
        run: mvn -B package --file pom.xml
      
      - name: Step 4 - List the current directory
        run: ls -a
      
      - name: Step 5 - List the Target Directory
        run: |
          cd target
          ls -a
  
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
